[DOWNSTREAM ONLY] lustre: update config HAVE_PARAM_SET_UINT_MINMAX
The following commit introduced in v5.4.278 exports the function
param_set_uint_minmax() and thus it no longer needs to be reimplemented
in the lustre code.

07b002723cf0 ("params: lift param_set_uint_minmax to common code")

Update the config to set HAVE_PARAM_SET_UINT_MINMAX so that it doesn't
get re-declared fixing the following build failure.

drivers/staging/lustrefsx/libcfs/libcfs/debug.c:204:12: error: static declaration of 'param_set_uint_minmax' follows non-static declaration
 static int param_set_uint_minmax(const char *val,
            ^~~~~~~~~~~~~~~~~~~~~
In file included from ./include/linux/module.h:18:0,
                 from ./drivers/staging/lustrefsx/libcfs/include/libcfs/libcfs.h:37,
                 from drivers/staging/lustrefsx/libcfs/libcfs/debug.c:42:
./include/linux/moduleparam.h:362:5: note: previous declaration of 'param_set_uint_minmax' was here
 int param_set_uint_minmax(const char *val, const struct kernel_param *kp,
     ^~~~~~~~~~~~~~~~~~~~~

This is not a candidate for upstream inclusion since the commit which
adds the lustre code is downstream only too.

Fixes: ea52a10ec0b9 ("lustre: update to AmazonFSxLustreClient v2.12.8-fsx")
Signed-off-by: Maximilian Heyne <mheyne@amazon.de>
Signed-off-by: Suraj Jitindar Singh <surajjs@amazon.com>